package webportal.HKSBO2.dailynav.repository;

import java.util.List;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import webportal.HKSBO2.entity.Vsbtradingacc;

public interface DailyNavRepository extends JpaRepository<Vsbtradingacc, String> {
  
  @Query(value = "WITH MARKETVALUE_HKEX AS ( " +
                 "SELECT TRADEDATE, AEID, CAST(SUM(MARKETVALUE * TOBASECURRENCYEXCHANGERATE) AS DECIMAL(18, 2)) AS MARKETVALUE_HKEX_HKD " +
                 "FROM VSBTRADINGACC " +
                 "WHERE MARKETID = 'HKEX' " +
                 "GROUP BY TRADEDATE, AEID), " +
                 "MARKETVALUE_MAMK AS ( " +
                 "SELECT TRADEDATE, AEID, CAST(SUM(MARKETVALUE * TOBASECURRENCYEXCHANGERATE) AS DECIMAL(18, 2)) AS MARKETVALUE_MAMK_HKD " +
                 "FROM VSBTRADINGACC " +
                 "WHERE MARKETID = 'MAMK' " +
                 "GROUP BY TRADEDATE, AEID), " +
                 "MARKETVALUE_SZMK AS ( " +
                 "SELECT TRADEDATE, AEID, CAST(SUM(MARKETVALUE * TOBASECURRENCYEXCHANGERATE) AS DECIMAL(18, 2)) AS MARKETVALUE_SZMK_HKD " +
                 "FROM VSBTRADINGACC " +
                 "WHERE MARKETID = 'SZMK' " +
                 "GROUP BY TRADEDATE, AEID), " +
                 "MARKETVALUE_USEX AS ( " +
                 "SELECT TRADEDATE, AEID, CAST(SUM(MARKETVALUE * TOBASECURRENCYEXCHANGERATE) AS DECIMAL(18, 2)) AS MARKETVALUE_USEX_HKD " +
                 "FROM VSBTRADINGACC " +
                 "WHERE MARKETID = 'USEX' " +
                 "GROUP BY TRADEDATE, AEID), " +
                 "MARKETVALUE_FUND AS ( " +
                 "SELECT TRADEDATE, AEID, CAST(SUM(MARKETVALUE * TOBASECURRENCYEXCHANGERATE) AS DECIMAL(18, 2)) AS MARKETVALUE_FUND_HKD " +
                 "FROM VSBTRADINGACC " +
                 "WHERE MARKETID = 'FUND' " +
                 "GROUP BY TRADEDATE, AEID), " +
                 "MARKETVALUE_OTHER AS ( " +
                 "SELECT TRADEDATE, AEID, CAST(SUM(MARKETVALUE * TOBASECURRENCYEXCHANGERATE) AS DECIMAL(18, 2)) AS MARKETVALUE_OTHER_HKD " +
                 "FROM VSBTRADINGACC " +
                 "WHERE MARKETID NOT IN ('HKEX', 'MAMK', 'SZMK', 'USEX', 'FUND') " +
                 "GROUP BY TRADEDATE, AEID) " +
                 "SELECT VARCHAR_FORMAT(VL.TRADEDATE, 'DD/MM/YYYY') AS DATE, VL.AEID, CAST(SUM(LEDGERBAL) AS DECIMAL(18, 2)) AS LEDGERBAL_HKD, " +
                 "COALESCE(MVH.MARKETVALUE_HKEX_HKD, 0) AS MARKETVALUE_HKEX_HKD, " +
                 "COALESCE(MVM.MARKETVALUE_MAMK_HKD, 0) AS MARKETVALUE_MAMK_HKD, " +
                 "COALESCE(MVS.MARKETVALUE_SZMK_HKD, 0) AS MARKETVALUE_SZMK_HKD, " +
                 "COALESCE(MVU.MARKETVALUE_USEX_HKD, 0) AS MARKETVALUE_USEX_HKD, " +
                 "COALESCE(MVF.MARKETVALUE_FUND_HKD, 0) AS MARKETVALUE_FUND_HKD, " +
                 "COALESCE(MVO.MARKETVALUE_OTHER_HKD, 0) AS MARKETVALUE_OTHER_HKD, " +
                 "COALESCE(MVH.MARKETVALUE_HKEX_HKD, 0) + COALESCE(MVM.MARKETVALUE_MAMK_HKD, 0) + COALESCE(MVS.MARKETVALUE_SZMK_HKD, 0) + " +
                 "COALESCE(MVU.MARKETVALUE_USEX_HKD, 0) + COALESCE(MVF.MARKETVALUE_FUND_HKD, 0) + COALESCE(MVO.MARKETVALUE_OTHER_HKD, 0) AS TOTAL_MARKETVALUE_HKD, " +
                 "COALESCE(MVH.MARKETVALUE_HKEX_HKD, 0) + COALESCE(MVM.MARKETVALUE_MAMK_HKD, 0) + COALESCE(MVS.MARKETVALUE_SZMK_HKD, 0) + " +
                 "COALESCE(MVU.MARKETVALUE_USEX_HKD, 0) + COALESCE(MVF.MARKETVALUE_FUND_HKD, 0) + COALESCE(MVO.MARKETVALUE_OTHER_HKD, 0) + " +
                 "CAST(SUM(LEDGERBAL) AS DECIMAL(18, 2)) AS NET_EQUITY " +
                 "FROM VCBACCOUNTSUMMARYEQD VL " +
                 "LEFT JOIN MARKETVALUE_HKEX MVH ON VL.TRADEDATE = MVH.TRADEDATE AND VL.AEID = MVH.AEID " +
                 "LEFT JOIN MARKETVALUE_MAMK MVM ON VL.TRADEDATE = MVM.TRADEDATE AND VL.AEID = MVM.AEID " +
                 "LEFT JOIN MARKETVALUE_SZMK MVS ON VL.TRADEDATE = MVS.TRADEDATE AND VL.AEID = MVS.AEID " +
                 "LEFT JOIN MARKETVALUE_USEX MVU ON VL.TRADEDATE = MVU.TRADEDATE AND VL.AEID = MVU.AEID " +
                 "LEFT JOIN MARKETVALUE_FUND MVF ON VL.TRADEDATE = MVF.TRADEDATE AND VL.AEID = MVF.AEID " +
                 "LEFT JOIN MARKETVALUE_OTHER MVO ON VL.TRADEDATE = MVO.TRADEDATE AND VL.AEID = MVO.AEID " +
                 "WHERE TOCURRENCYID = 'HKD' " +
                 "GROUP BY VL.TRADEDATE, MVH.MARKETVALUE_HKEX_HKD, MVM.MARKETVALUE_MAMK_HKD, MVS.MARKETVALUE_SZMK_HKD, MVU.MARKETVALUE_USEX_HKD, " +
                 "MVF.MARKETVALUE_FUND_HKD, MVO.MARKETVALUE_OTHER_HKD, VL.AEID " +
                 "HAVING VL.TRADEDATE BETWEEN :startdate AND :enddate " +
                 "ORDER BY VL.TRADEDATE", nativeQuery = true)
  List<Object[]> getDailyNav(@Param("startdate") String startdate, @Param("enddate") String enddate);

}